version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
